version: "3.9"
services:
  fileio:
    container_name: "fileIo_service"
    build:
      context: ./FileIO
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
    stdin_open: true
  root:
    container_name: "root_service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    environment:
      DISPLAY: host.docker.internal:0